### ISSUE TITLE
[FEAT REQ] Uninstall Make rule

### ISSUE THREAD

**Issue by agsuy** [FedeDP/Clightd#107]
It would be great to be able to remove Clightd without manually tracking and removing everything.

**Comment by FedeDP** [comment]
Hi! Thanks for opening this request. Unfortunately, cmake does not offer such an option.
Luckily enough, there are some workarounds: https://stackoverflow.com/questions/41471620/cmake-support-make-uninstall

I could also implement the uninstall target manually, but I'd avoid doing so (since the aforementioned workarounds work just fine!).
I can add an entry in the Wiki pages perhaps?

**Comment by agsuy** [comment]
Hello! Thanks for the quick response.

Yup, I ended doing something similar piping with `xargs` to `rm` 

Just mentioning the preferred way to uninstall (maybe provide a snippet or how to entry) should suffice and make things easier for end users.

**Comment by FedeDP** [comment]
Added :) 
https://github.com/FedeDP/Clightd/wiki/Build#uninstallation

Thank you for your feedback!
