### ISSUE TITLE
libmodule 5.0.0

### ISSUE THREAD

**Issue by vivien** [FedeDP/Clightd#32]
clightd installation fails because of out-of-date libmodule AUR

````
--   Package dependency requirement 'libmodule >= 5.0.0' could not be satisfied.
Package 'libmodule' has version '4.2.0', required version is '>= 5.0.0'
````

**Comment by FedeDP** [comment]
This is unfortunately well known: clight-git and clightd-git depend upon libmodule >= 5.0.0 that is released but not yet available in aur.
This is because libmodule 5.0.0 update would break current clight/clightd 3.X installations caused by API breaks.

I'm planning to release new Clightd/Clight as soon as possible (well those were planned like 1.5 months ago indeed...).

Sorry for the inconvenience, i really badly managed this release.

EDIT: in the meantime you could change libmodule PKGBUILD to build 5.0.0 instead, copying by: https://raw.githubusercontent.com/FedeDP/libmodule/master/Extra/Arch/PKGBUILD.

**Comment by vivien** [comment]
> EDIT: in the meantime you could change libmodule PKGBUILD to build 5.0.0 instead, copying by: https://raw.githubusercontent.com/FedeDP/libmodule/master/Extra/Arch/PKGBUILD.

Done, thank you! There's still no clean way to provide systemd user unit file for clight, right?

**Comment by FedeDP** [comment]
Unfortunately no: as far as I know there is no easy way to actually start clight after X session has been started.
But I recently saw that Gnome is moving towards systemd user sessions and kde is kinda following (at least for Linux builds).
May be in the near future it will be possible!

**Comment by vivien** [comment]
Yay, let's keep an eye on this!
