### ISSUE TITLE
[FEATURE REQ] Configure used VCP code

### ISSUE THREAD

**Issue by Ashymad** [FedeDP/Clightd#37]
Sadly not every manufacturer conforms to the specification and on some monitors brightness might be controlled by some other VCP code than 0x10. On my external Fujitsu monitors OSD "Brightness" is controlled by VCP code 0x6b (Backlight Level: White), while 0x10 changes something called "Black Level" in the OSD, which I would rather set at a constant value, high values of this make everything unreadable.

**Comment by FedeDP** [comment]
Hi!
Thanks for opening the issue!
This is a nice idea indeed, that surely needs to be implemented :)
I hope to include it for the next release (no eta unfortunately!).
In the meantime you can patch your clightd4.0 sources :)

**Comment by Ashymad** [comment]
>  In the meantime you can patch your clightd4.0 sources :)

Yup, that's what I'm doing right now :)

**Comment by FedeDP** [comment]
Fixed by commit 14d0bded9d14921939f4dd40e857c292010aba10.
Is is exposed as a cmdline parameter ("--vpcode 0xYY"): you can simply override default clightd service with your own (https://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services) and you should be good to go. 
It is still in devel branch though. This will appear in next release!
Thank you again!

**Comment by FedeDP** [comment]
And wiki page updated: https://github.com/FedeDP/Clightd/wiki/Getting-Started#cmdline-parameters :)
